[workspace]
members = [
    "tjuptop",
    "server",
    "util",
]
default-members = [
    "tjuptop",
    "server",
]


[profile.release]
opt-level = "s"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
