top = [
    "08:00:00",
    "20:00:00",
    "00:00:00",
    "18:00:00",
    "22:00:00",
    "07:00:00",
    "06:00:00",
    "12:00:00",
]

[[users]]
name = "username"
pwd = "password"

[network]
delay = 1000
answer = 10
post = 10

[email]
username = "username@qq.com"
password = "password"
from = "from <from@email.com>"
to = "to <to@email.com>"
host = "smtp.host.com"
port = 465
