# 示例配置文件, 展示高级设置

# 在此填写用户信息，可以指定多个
[[users]]
# 用户名
name = "用户名"
# 密码
pwd = "密码"

[[users]]
name = "用户名2"
pwd = "密码2" 

# 全局设置
[global]
retry = 1

# 邮件设置
# 用来发送邮件提醒
[global.emailconf]
# 登陆名
user = "登录名"
# 发件人，可以不指定
sender = "发件人"
# 登陆密码
pwd = "pwd"

# smtp设置，如果不指定则是 smtp.qq.com
host = "smtp.qq.com"
# 端口，如果不指定则是465
port = 465
