[package]
name = "util"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"

[dependencies.chrono]
version = "0.4"
default-features = false
features = ["clock", "std", "serde"]
