name: Release

on:
  push:
    # branches: master
    tags:
      - 'v*.*.*'

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup MUSL
      if: matrix.os == 'ubuntu-latest'
      run: |
        rustup target add x86_64-unknown-linux-musl
        sudo apt-get -q install musl-tools

    - name: Build for linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        make release_lnx

    - name: Build for macOS
      if: matrix.os == 'macOS-latest'
      run: make release_mac

    - name: Build for Windows
      if: matrix.os == 'windows-latest'
      run: make release_win

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        files: |
          *.zip
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE }}
